name: Build MAUI app

on:
  pull_request:  
  push:
    branches:
      - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.303
          include-prerelease: true
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources
      - name: Restore Dependencies
        run: dotnet restore ./MauiApp1/MauiApp1.csproj

      - name: Build MAUI Android
        run: dotnet build ./MauiApp1/MauiApp1.csproj -c Release -f net6.0-android --no-restore

      - name: Build MAUI Android
        run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f net6.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: maui-android-ci-build
          path: MauiApp1/bin/Release/net6.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.303

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MauiApp1/MauiApp1.csproj

      - name: Build MAUI Windows
        run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f net6.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: maui-windows-ci-build
          path: MauiApp1/bin/Release/net6.0-windows10.0.19041.0/win10-x64/AppPackages/MauiApp*/MauiApp*.msix


# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.303

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MauiApp1/MauiApp1.csproj

      - name: Build MAUI iOS
        run: dotnet build MauiApp1/MauiApp1.csproj -c Release -f net6.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: maui-ios-ci-build
          path: MauiApp1/bin/Release/net6.0-ios/iossimulator-x64/**/*.app


# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.303

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MauiApp1/MauiApp1.csproj

      - name: Build MAUI MacCatalyst
        run: dotnet publish MauiApp1/MauiApp1.csproj -c Release -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: mauibeach-macos-ci-build
          path: MauiApp1/bin/Release/net6.0-maccatalyst/maccatalyst-x64/publish/*.pkg

